import tkinter as tk
from tkinter import filedialog, messagebox
from tkinter import ttk
from fpdf import FPDF
import os
from PyPDF2 import PdfReader
from docx import Document
import requests
from transformers import pipeline
from bs4 import BeautifulSoup
from ddgs import DDGS
import wikipedia
import re  # Added import for regular expressions

# ---------------------------------
# Load summarizer
# ---------------------------------
summarizer = pipeline("summarization", model="facebook/bart-large-cnn")

# ---------------------------------
# Helper Functions
# ---------------------------------
def fetch_article_text(url):
    """Fetch visible text from a webpage."""
    try:
        headers = {'User-Agent': 'Mozilla/5.0'}
        r = requests.get(url, headers=headers, timeout=10)
        soup = BeautifulSoup(r.text, "html.parser")
        for tag in soup(["script", "style", "header", "footer", "nav"]):
            tag.decompose()
        text = " ".join(p.get_text().strip() for p in soup.find_all("p"))
        return text
    except Exception:
        return ""

def get_search_text(query):
    """Get web content from DDGS or Wikipedia."""
    combined_text = ""
    try:
        with DDGS() as ddgs:
            results = [r for r in ddgs.text(query, max_results=5)]
            urls = [r.get("href") or r.get("url") for r in results if r.get("href") or r.get("url")]
        for url in urls:
            article = fetch_article_text(url)
            if len(article) > 800:
                combined_text += article + " "
    except Exception:
        pass

    # Fallback: Wikipedia
    if not combined_text:
        try:
            summary = wikipedia.page(query, auto_suggest=True).content
            combined_text = summary[:10000]
        except Exception:
            combined_text = ""
    return combined_text.strip()

def summarize_text(text, topic):
    """Summarize and beautify notes."""
    if not text.strip():
        return "⚠️ No text found to summarize."

    chunks = [text[i:i+4000] for i in range(0, len(text), 4000)]
    summaries = []
    for chunk in chunks:
        summary = summarizer(chunk, max_length=220, min_length=80, do_sample=False)[0]['summary_text']
        summaries.append(summary)

    full_summary = " ".join(summaries)

    # Break into note-like structure
    sentences = [s.strip().capitalize() for s in full_summary.split('.') if len(s.strip()) > 25]
    sections = {
        "Overview": sentences[:3],
        "Key Concepts": sentences[3:7],
        "Applications": sentences[7:],
    }

    formatted = f"## 🧠 Study Notes on {topic.title()}\n"
    for title, points in sections.items():
        if points:
            formatted += f"\n### 🔹 {title}\n"
            for p in points:
                formatted += f"- {p}.\n"
    formatted += "\n---\n✅ *Generated by StudyMate AI*"
    return formatted

def extract_text_from_file(file_path):
    """Extract text from uploaded files."""
    ext = os.path.splitext(file_path)[1].lower()
    text = ""
    if ext == ".pdf":
        pdf = PdfReader(file_path)
        text = " ".join([page.extract_text() for page in pdf.pages if page.extract_text()])
    elif ext == ".docx":
        doc = Document(file_path)
        text = " ".join([p.text for p in doc.paragraphs])
    elif ext == ".txt":
        with open(file_path, "r", encoding="utf-8") as file:
            text = file.read()
    return text

def clean_text_for_pdf(text):
    """Clean the text by removing non-ASCII characters (like emojis) that cannot be encoded in Latin-1."""
    # Remove any characters that are not ASCII (e.g., emojis)
    cleaned_text = re.sub(r'[^\x00-\x7F]+', '', text)
    return cleaned_text

def save_notes_as_pdf(topic, notes, save_path):
    """Save generated notes to PDF at the specified path."""
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.set_font("Arial", size=12)

    # Clean the notes text to remove non-ASCII characters
    notes = clean_text_for_pdf(notes)

    pdf.multi_cell(0, 10, notes)
    pdf.output(save_path)
    messagebox.showinfo("Success", f"Notes saved as {save_path}")

# ---------------------------------
# Tkinter UI Setup
# ---------------------------------
root = tk.Tk()
root.title("StudyMate AI — Smart Notes Generator")
root.geometry("600x500")
root.config(bg="#F5F5F5")

# Colors
button_color = "#4CAF50"
generate_button_color = "#2196F3"
save_button_color = "#FF5722"

# Labels
tk.Label(root, text="Enter a Topic or Upload a File:", font=("Arial", 14), bg="#F5F5F5").pack(pady=10)
topic_entry = tk.Entry(root, font=("Arial", 12), width=40)
topic_entry.pack(pady=5)

# File Upload Section
tk.Label(root, text="Upload File:", font=("Arial", 14), bg="#F5F5F5").pack(pady=10)
file_label = tk.Label(root, text="No file selected", font=("Arial", 12), fg="gray", bg="#F5F5F5")
file_label.pack(pady=5)

def choose_file():
    file_path = filedialog.askopenfilename(filetypes=[("All Files", "*.*"), ("Text Files", "*.txt"), ("PDF Files", "*.pdf"), ("Word Files", "*.docx")])
    if file_path:
        file_label.config(text=file_path)

def deselect_file():
    file_label.config(text="No file selected")

upload_button = tk.Button(root, text="Choose File", font=("Arial", 12), bg=button_color, fg="white", command=choose_file)
upload_button.pack(pady=5)

deselect_button = tk.Button(root, text="Deselect File", font=("Arial", 12), bg="red", fg="white", command=deselect_file)
deselect_button.pack(pady=5)

# Output area for generated notes
generated_notes_label = tk.Label(root, text="Generated Notes:", font=("Arial", 14), bg="#F5F5F5")
generated_notes_label.pack(pady=10)

notes_output = tk.Text(root, font=("Arial", 12), width=70, height=10)
notes_output.pack(pady=5)

# Generate Notes Button
def generate_notes():
    topic = topic_entry.get().strip()
    if not topic and file_label.cget("text") == "No file selected":
        messagebox.showwarning("Input Error", "Please enter a topic or upload a file.")
        return

    text_data = ""
    if topic:
        text_data = get_search_text(topic)
    if file_label.cget("text") != "No file selected":
        text_data = extract_text_from_file(file_label.cget("text"))

    if text_data:
        notes = summarize_text(text_data, topic if topic else "Study Notes")
        notes_output.delete(1.0, tk.END)
        notes_output.insert(tk.END, notes)
    else:
        messagebox.showwarning("No Content", "Unable to extract text from the file or search topic.")

generate_button = tk.Button(root, text="Generate Notes", font=("Arial", 12), bg=generate_button_color, fg="white", command=generate_notes)
generate_button.pack(pady=10)

# Save Notes as PDF Button
def save_pdf():
    topic = topic_entry.get().strip()
    notes = notes_output.get(1.0, tk.END).strip()
    if notes:
        # Open file save dialog to let the user choose where to save the file
        save_path = filedialog.asksaveasfilename(defaultextension=".pdf", filetypes=[("PDF Files", "*.pdf")])
        if save_path:
            save_notes_as_pdf(topic if topic else "StudyNotes", notes, save_path)
    else:
        messagebox.showwarning("No Notes", "No notes to save as PDF.")

save_pdf_button = tk.Button(root, text="Save Notes as PDF", font=("Arial", 12), bg=save_button_color, fg="white", command=save_pdf)
save_pdf_button.pack(pady=10)

# Start the Tkinter event loop
root.mainloop()
